spring:
    datasource:
        url: jdbc:h2:mem:students
        platform: h2
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        properties:
            hibernate:
                show_sql: true
