openapi: 3.0.0
info:
    title: Students
    description: >-
        Popis

        Druhý odstavec popisu.

        Nějaký **tučný** text.
    version: 1.0.0

paths:

    /students:
        summary: Summary for the whole path.
        description: Description for the whole path.

        get:
            summary: Summary for the operation.
            description: >-
                Description for the operation.

                Second paragraph of the description.
            operationId: getStudents
            responses:
                200:
                    description: Description
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Student"

        post:
            summary: Summary
            description: Description
            operationId: postStudent
            requestBody:
                $ref: "#/components/requestBodies/student"
            responses:
                201:
                    description: Description

    /students/{studentId}:
        summary: Summary
        description: Description

        get:
            summary: Summary
            description: Description
            operationId: getStudent
            parameters:
                - $ref: "#/components/parameters/studentId"
            responses:
                200:
                    description: Description
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Student"
                404:
                    description: When the student cannot be found

        put:
            summary: Summary
            description: Description
            operationId: putStudent
            parameters:
                - $ref: "#/components/parameters/studentId"
            requestBody:
                $ref: "#/components/requestBodies/student"
            responses:
                204:
                    description: Description

        delete:
            summary: Summary
            description: Description
            operationId: deleteStudent
            parameters:
                - $ref: "#/components/parameters/studentId"
            responses:
                204:
                    description: Description

components:
    parameters:
        studentId:
            name: studentId
            description: Description
            in: path
            required: true
            schema:
                type: integer
                format: int64
    requestBodies:
        student:
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Student"
    schemas:
        Student:
            description: Student description
            type: object
            properties:
                id:
                    description: Id
                    type: integer
                    format: int64
                firstName:
                    description: First name of the student
                    type: string
                lastName:
                    description: Last name of the student
                    type: string
                year:
                    description: Year the student currently is in
                    type: integer
                    format: int32
                    minimum: 1
                    maximum: 7
            required:
                - firstName
                - lastName
                - year
