/**
 * Students
 * Popis Druhý odstavec popisu. Nějaký **tučný** text.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The StudentDto model module.
* @module dto/StudentDto
* @version 1.0.0
*/
export default class StudentDto {
    /**
    * Constructs a new <code>StudentDto</code>.
    * Student description
    * @alias module:dto/StudentDto
    * @class
    * @param firstName {String} First name of the student
    * @param lastName {String} Last name of the student
    * @param year {Number} Year the student currently is in
    */

    constructor(firstName, lastName, year) {
        

        
        

        this['firstName'] = firstName;this['lastName'] = lastName;this['year'] = year;

        
    }

    /**
    * Constructs a <code>StudentDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:dto/StudentDto} obj Optional instance to populate.
    * @return {module:dto/StudentDto} The populated <code>StudentDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StudentDto();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Id
    * @member {Number} id
    */
    id = undefined;
    /**
    * First name of the student
    * @member {String} firstName
    */
    firstName = undefined;
    /**
    * Last name of the student
    * @member {String} lastName
    */
    lastName = undefined;
    /**
    * Year the student currently is in
    * @member {Number} year
    */
    year = undefined;








}


