/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Students
 * Popis Druhý odstavec popisu. Nějaký **tučný** text.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * Student description
 * @export
 * @interface StudentDto
 */
export interface StudentDto {
    /**
     * Id
     * @type {number}
     * @memberof StudentDto
     */
    id?: number;
    /**
     * First name of the student
     * @type {string}
     * @memberof StudentDto
     */
    firstName: string;
    /**
     * Last name of the student
     * @type {string}
     * @memberof StudentDto
     */
    lastName: string;
    /**
     * Year the student currently is in
     * @type {number}
     * @memberof StudentDto
     */
    year: number;
}


/**
 * DefaultApi - fetch parameter creator
 * @export
 */
export const DefaultApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Description
         * @summary Summary
         * @param {number} studentId Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStudent(studentId: number, options: any = {}): FetchArgs {
            // verify required parameter 'studentId' is not null or undefined
            if (studentId === null || studentId === undefined) {
                throw new RequiredError('studentId','Required parameter studentId was null or undefined when calling deleteStudent.');
            }
            const localVarPath = `/students/{studentId}`
                .replace(`{${"studentId"}}`, encodeURIComponent(String(studentId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Description
         * @summary Summary
         * @param {number} studentId Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudent(studentId: number, options: any = {}): FetchArgs {
            // verify required parameter 'studentId' is not null or undefined
            if (studentId === null || studentId === undefined) {
                throw new RequiredError('studentId','Required parameter studentId was null or undefined when calling getStudent.');
            }
            const localVarPath = `/students/{studentId}`
                .replace(`{${"studentId"}}`, encodeURIComponent(String(studentId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Description for the operation. Second paragraph of the description.
         * @summary Summary for the operation.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudents(options: any = {}): FetchArgs {
            const localVarPath = `/students`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Description
         * @summary Summary
         * @param {StudentDto} student Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postStudent(student: StudentDto, options: any = {}): FetchArgs {
            // verify required parameter 'student' is not null or undefined
            if (student === null || student === undefined) {
                throw new RequiredError('student','Required parameter student was null or undefined when calling postStudent.');
            }
            const localVarPath = `/students`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"StudentDto" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(student || {}) : (student || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Description
         * @summary Summary
         * @param {number} studentId Description
         * @param {StudentDto} student Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putStudent(studentId: number, student: StudentDto, options: any = {}): FetchArgs {
            // verify required parameter 'studentId' is not null or undefined
            if (studentId === null || studentId === undefined) {
                throw new RequiredError('studentId','Required parameter studentId was null or undefined when calling putStudent.');
            }
            // verify required parameter 'student' is not null or undefined
            if (student === null || student === undefined) {
                throw new RequiredError('student','Required parameter student was null or undefined when calling putStudent.');
            }
            const localVarPath = `/students/{studentId}`
                .replace(`{${"studentId"}}`, encodeURIComponent(String(studentId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"StudentDto" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(student || {}) : (student || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Description
         * @summary Summary
         * @param {number} studentId Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStudent(studentId: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).deleteStudent(studentId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Description
         * @summary Summary
         * @param {number} studentId Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudent(studentId: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<StudentDto> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).getStudent(studentId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Description for the operation. Second paragraph of the description.
         * @summary Summary for the operation.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudents(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<StudentDto>> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).getStudents(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Description
         * @summary Summary
         * @param {StudentDto} student Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postStudent(student: StudentDto, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<number> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).postStudent(student, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Description
         * @summary Summary
         * @param {number} studentId Description
         * @param {StudentDto} student Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putStudent(studentId: number, student: StudentDto, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).putStudent(studentId, student, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Description
         * @summary Summary
         * @param {number} studentId Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStudent(studentId: number, options?: any) {
            return DefaultApiFp(configuration).deleteStudent(studentId, options)(fetch, basePath);
        },
        /**
         * Description
         * @summary Summary
         * @param {number} studentId Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudent(studentId: number, options?: any) {
            return DefaultApiFp(configuration).getStudent(studentId, options)(fetch, basePath);
        },
        /**
         * Description for the operation. Second paragraph of the description.
         * @summary Summary for the operation.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStudents(options?: any) {
            return DefaultApiFp(configuration).getStudents(options)(fetch, basePath);
        },
        /**
         * Description
         * @summary Summary
         * @param {StudentDto} student Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postStudent(student: StudentDto, options?: any) {
            return DefaultApiFp(configuration).postStudent(student, options)(fetch, basePath);
        },
        /**
         * Description
         * @summary Summary
         * @param {number} studentId Description
         * @param {StudentDto} student Description
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putStudent(studentId: number, student: StudentDto, options?: any) {
            return DefaultApiFp(configuration).putStudent(studentId, student, options)(fetch, basePath);
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Description
     * @summary Summary
     * @param {} studentId Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteStudent(studentId: number, options?: any) {
        return DefaultApiFp(this.configuration).deleteStudent(studentId, options)(this.fetch, this.basePath);
    }

    /**
     * Description
     * @summary Summary
     * @param {} studentId Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getStudent(studentId: number, options?: any) {
        return DefaultApiFp(this.configuration).getStudent(studentId, options)(this.fetch, this.basePath);
    }

    /**
     * Description for the operation. Second paragraph of the description.
     * @summary Summary for the operation.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getStudents(options?: any) {
        return DefaultApiFp(this.configuration).getStudents(options)(this.fetch, this.basePath);
    }

    /**
     * Description
     * @summary Summary
     * @param {} student Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postStudent(student: StudentDto, options?: any) {
        return DefaultApiFp(this.configuration).postStudent(student, options)(this.fetch, this.basePath);
    }

    /**
     * Description
     * @summary Summary
     * @param {} studentId Description
     * @param {} student Description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public putStudent(studentId: number, student: StudentDto, options?: any) {
        return DefaultApiFp(this.configuration).putStudent(studentId, student, options)(this.fetch, this.basePath);
    }

}

